services:
  frontend:
#    build:
#      context: .
#      dockerfile: dockerfile
    container_name: inventory_dashboard_frontend
    image: resilientbd/inventory-dashboard:latest
    ports:
      - "8080:80"
    restart: always
